/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Sredko, SredkoInterface } from "../Sredko";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Sent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "minter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b0319163317905561028d806100326000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063075461721461005157806327e235e31461008257806340c10f19146100c7578063d0679d3414610102575b600080fd5b61005961013b565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b6100b56004803603602081101561009857600080fd5b503573ffffffffffffffffffffffffffffffffffffffff16610157565b60408051918252519081900360200190f35b610100600480360360408110156100dd57600080fd5b5073ffffffffffffffffffffffffffffffffffffffff8135169060200135610169565b005b6101006004803603604081101561011857600080fd5b5073ffffffffffffffffffffffffffffffffffffffff81351690602001356101bd565b60005473ffffffffffffffffffffffffffffffffffffffff1681565b60016020526000908152604090205481565b60005473ffffffffffffffffffffffffffffffffffffffff16331461018d576101b9565b73ffffffffffffffffffffffffffffffffffffffff821660009081526001602052604090208054820190555b5050565b336000908152600160205260409020548111156101d9576101b9565b3360008181526001602090815260408083208054869003905573ffffffffffffffffffffffffffffffffffffffff861680845292819020805486019055805193845290830191909152818101839052517f3990db2d31862302a685e8086b5755072a6e2b5b780af1ee81ece35ee3cd33459181900360600190a1505056fea26469706673582212201b472ad74ce14a179ebb3accc45bcfcf4cc705d4f59f3135d93cec36eb9f257864736f6c63430007060033";

export class Sredko__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Sredko> {
    return super.deploy(overrides || {}) as Promise<Sredko>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Sredko {
    return super.attach(address) as Sredko;
  }
  connect(signer: Signer): Sredko__factory {
    return super.connect(signer) as Sredko__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SredkoInterface {
    return new utils.Interface(_abi) as SredkoInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Sredko {
    return new Contract(address, _abi, signerOrProvider) as Sredko;
  }
}
